#@TYPE: Machine
#@NAME: Henhouse Controller based on RPI Zero W
#@DESCRIPTION: Henhouse Controller

require conf/machine/raspberrypi0-wifi.conf

MACHINEOVERRIDES =. "raspberrypi0-wifi:"

# TOOD: This is needed when using core-image-minimal, when everythinks works fine, it may be deleted
# MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS_append = " \
#      wpa-supplicant \
#      linux-firmware-rpidistro-bcm43430 \
#      kernel-modules \
#      udev-rules-rpi \
# "

MACHINE_FEATURES_remove = " screen touchscreen alsa"

### Enables uboot - raspberrypi specific
RPI_USE_U_BOOT = "1"

### Enables UART - raspberrypi specific
ENABLE_UART = "1"

### Without this, there is an additional check in runtime and write to inittab
SERIAL_CONSOLES_CHECK = ""

### HW PWM support on board ###
KERNEL_DEVICETREE_append = " overlays/pwm.dtbo"
RPI_EXTRA_CONFIG_append = " dtoverlay=pwm,pin=12,func=4"