#@TYPE: Machine
#@NAME: Henhouse Controller based on RPI Zero W
#@DESCRIPTION: Henhouse Controller

require conf/machine/raspberrypi0-wifi.conf

MACHINEOVERRIDES =. "raspberrypi0-wifi:"

### Options for meta-raspberrypi ###
RPI_USE_U_BOOT = "1"
ENABLE_UART = "1"