# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "bsp_embedos"
BBFILE_PATTERN_bsp_embedos = "^${LAYERDIR}/"
BBFILE_PRIORITY_bsp_embedos = "6"

LAYERDEPENDS_bsp_embedos = "core"
LAYERDEPENDS_bsp_embedos = "raspberrypi"
LAYERSERIES_COMPAT_bsp_embedos = "gatesgarth"

## TODO: Rename to sth more resembling board like hhhctrl-bsp-etc