

#
# An example of subclassing a distro, primarily used for testing alternate configuration
# combinations on the Yocto Project autobuilder
#

require conf/distro/include/common.conf

DISTRO = "sheli-integration"
DISTRO_NAME = "Sheli-Integration (Smart Home Embedded Linux)"
DISTRO_VERSION = "1.0.0"
DISTRO_STAGE = "integration"
DISTROOVERRIDES = "poky:sheli-integration"

